# Generated by Django 2.0.6 on 2018-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extr_no', models.CharField(max_length=30, verbose_name='序号')),
                ('src_sys', models.CharField(max_length=30, verbose_name='源系统编号')),
                ('src_tab_nm', models.CharField(max_length=30, verbose_name='源系统表名')),
                ('extr_condition', models.CharField(max_length=200, verbose_name='抽取条件')),
                ('extr_freq', models.CharField(max_length=30, verbose_name='抽取频度')),
                ('save_freq', models.CharField(max_length=30, verbose_name='保留周期')),
                ('start_dt', models.CharField(max_length=8, verbose_name='生效日期')),
                ('end_dt', models.CharField(max_length=8, verbose_name='失效日期')),
                ('c_oper_no', models.CharField(max_length=30, verbose_name='创建人员')),
                ('c_dt', models.CharField(max_length=8, verbose_name='创建日期')),
                ('m_oper_no', models.CharField(max_length=30, verbose_name='修改人员')),
                ('m_dt', models.CharField(max_length=8, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '配置表-源表抽取',
                'verbose_name_plural': '配置表-源表抽取',
            },
        ),
        migrations.CreateModel(
            name='SrcDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_sys', models.CharField(max_length=30, verbose_name='源系统编号')),
                ('src_nm', models.CharField(max_length=200, verbose_name='源系统名称')),
                ('src_type', models.CharField(max_length=50, verbose_name='数据库类型')),
                ('src_user', models.CharField(max_length=50, verbose_name='用户名称')),
                ('src_pwd', models.CharField(max_length=50, verbose_name='密码')),
                ('src_ip', models.CharField(max_length=50, verbose_name='IP地址')),
                ('src_port', models.CharField(max_length=50, verbose_name='端口')),
                ('src_instance', models.CharField(max_length=50, verbose_name='实例名称')),
                ('start_dt', models.CharField(max_length=8, verbose_name='生效日期')),
                ('end_dt', models.CharField(max_length=8, verbose_name='失效日期')),
                ('c_oper_no', models.CharField(max_length=30, verbose_name='创建人员')),
                ('c_dt', models.CharField(max_length=8, verbose_name='创建日期')),
                ('m_oper_no', models.CharField(max_length=30, verbose_name='修改人员')),
                ('m_dt', models.CharField(max_length=8, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '配置表-源系统配置',
                'verbose_name_plural': '配置表-源系统配置',
            },
        ),
    ]
