# Generated by Django 2.0.6 on 2018-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hbasecatelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns', models.CharField(max_length=30, verbose_name='tableNamespace')),
                ('tn', models.CharField(max_length=30, verbose_name='tableName')),
                ('rk', models.CharField(max_length=30, verbose_name='rowkey')),
                ('dm', models.CharField(max_length=200, verbose_name='domain')),
                ('cf', models.CharField(max_length=30, verbose_name='columnFamily')),
                ('cn', models.CharField(max_length=30, verbose_name='columnName')),
                ('ct', models.CharField(max_length=30, verbose_name='columnType')),
            ],
            options={
                'verbose_name': '配置表-HBASECATELOG',
                'verbose_name_plural': '配置表-HBASECATELOG',
            },
        ),
        migrations.AlterModelOptions(
            name='extr',
            options={'verbose_name': '配置表-源表抽取配置', 'verbose_name_plural': '配置表-源表抽取配置'},
        ),
    ]
