# Generated by Django 2.0.6 on 2018-07-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0002_auto_20180717_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hbasecatelog',
            name='cn',
        ),
        migrations.RemoveField(
            model_name='hbasecatelog',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='hbasecatelog',
            name='dm',
        ),
        migrations.RemoveField(
            model_name='hbasecatelog',
            name='ns',
        ),
        migrations.RemoveField(
            model_name='hbasecatelog',
            name='rk',
        ),
        migrations.RemoveField(
            model_name='hbasecatelog',
            name='tn',
        ),
        migrations.AddField(
            model_name='hbasecatelog',
            name='col',
            field=models.CharField(default='', max_length=30, verbose_name='columnName'),
        ),
        migrations.AddField(
            model_name='hbasecatelog',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='tableName'),
        ),
        migrations.AddField(
            model_name='hbasecatelog',
            name='namespace',
            field=models.CharField(default='', max_length=50, verbose_name='tableNamespace'),
        ),
        migrations.AddField(
            model_name='hbasecatelog',
            name='type',
            field=models.CharField(default='', max_length=30, verbose_name='columnType'),
        ),
        migrations.AlterField(
            model_name='hbasecatelog',
            name='cf',
            field=models.CharField(default='', max_length=30, verbose_name='columnFamily'),
        ),
    ]
