# Generated by Django 2.0.6 on 2018-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0004_auto_20180719_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_no', models.CharField(default='', max_length=30, verbose_name='维度编号')),
                ('dim_desc', models.CharField(default='', max_length=200, verbose_name='维度名称')),
                ('dim_cd', models.CharField(default='', max_length=30, verbose_name='维度代码')),
                ('dim_nm', models.CharField(default='', max_length=200, verbose_name='维度名称')),
                ('f_dim_cd', models.CharField(default='', max_length=30, verbose_name='父维度代码')),
                ('dim_lv', models.CharField(default='', max_length=10, verbose_name='维度层级')),
                ('remark', models.CharField(default='', max_length=500, verbose_name='备注')),
                ('bel_depo_no', models.CharField(default='', max_length=30, verbose_name='归属部门')),
                ('bel_oper_no', models.CharField(default='', max_length=30, verbose_name='归属人员')),
                ('dim_src', models.CharField(default='', max_length=30, verbose_name='维度来源')),
                ('start_dt', models.CharField(default='', max_length=8, verbose_name='生效日期')),
                ('end_dt', models.CharField(default='', max_length=8, verbose_name='失效日期')),
                ('c_oper_no', models.CharField(default='', max_length=30, verbose_name='创建人员')),
                ('c_dt', models.CharField(default='', max_length=8, verbose_name='创建时间')),
                ('m_oper_no', models.CharField(default='', max_length=30, verbose_name='修改人员')),
                ('m_dt', models.CharField(default='', max_length=8, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '维度表',
                'verbose_name_plural': '维度表',
            },
        ),
        migrations.CreateModel(
            name='DefInd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_no', models.CharField(default='', max_length=30, verbose_name='指标编号')),
                ('ind_nm', models.CharField(default='', max_length=200, verbose_name='指标名称')),
                ('ind_prop', models.CharField(default='', max_length=30, verbose_name='指标属性')),
                ('ind_freq', models.CharField(default='', max_length=30, verbose_name='指标频度')),
                ('ind_biz_type', models.CharField(default='', max_length=30, verbose_name='业务类型')),
                ('ind_src', models.CharField(default='', max_length=100, verbose_name='指标来源')),
                ('ind_biz_cali_desc', models.CharField(default='', max_length=3000, verbose_name='业务口径描述')),
                ('ind_biz_cali_file', models.CharField(default='', max_length=3000, verbose_name='业务口径附件')),
                ('ind_biz_cali_file_nm', models.CharField(default='', max_length=200, verbose_name='业务口径附件名称')),
                ('ind_tech_cali_desc', models.CharField(default='', max_length=3000, verbose_name='技术口径描述')),
                ('ind_tech_cali_file', models.CharField(default='', max_length=3000, verbose_name='技术口径附件')),
                ('ind_tech_cali_file_nm', models.CharField(default='', max_length=200, verbose_name='技术口径附件名称')),
                ('ind_version', models.CharField(default='', max_length=30, verbose_name='指标版本号')),
                ('start_dt', models.CharField(default='', max_length=8, verbose_name='生效日期')),
                ('end_dt', models.CharField(default='', max_length=8, verbose_name='失效日期')),
                ('bel_depo_no', models.CharField(default='', max_length=30, verbose_name='归属部门')),
                ('bel_oper_no', models.CharField(default='', max_length=30, verbose_name='归属人员')),
                ('c_oper_no', models.CharField(default='', max_length=30, verbose_name='创建人员')),
                ('c_dt', models.CharField(default='', max_length=8, verbose_name='创建日期')),
                ('m_oper_no', models.CharField(default='', max_length=30, verbose_name='修改人员')),
            ],
            options={
                'verbose_name': '指标表',
                'verbose_name_plural': '指标表',
            },
        ),
        migrations.CreateModel(
            name='IndDimRela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_no', models.CharField(default='', max_length=30, verbose_name='指标编号')),
                ('dim_no', models.CharField(default='', max_length=30, verbose_name='维度编号')),
                ('start_dt', models.CharField(default='', max_length=8, verbose_name='生效日期')),
                ('end_dt', models.CharField(default='', max_length=8, verbose_name='失效日期')),
                ('c_oper_no', models.CharField(default='', max_length=30, verbose_name='创建人员')),
                ('c_dt', models.CharField(default='', max_length=8, verbose_name='创建日期')),
                ('m_oper_no', models.CharField(default='', max_length=30, verbose_name='修改人员')),
                ('m_dt', models.CharField(default='', max_length=8, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '指标维度',
                'verbose_name_plural': '指标维度',
            },
        ),
        migrations.CreateModel(
            name='Par',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_type', models.CharField(default='', max_length=30, verbose_name='参数类型')),
                ('par_type_nm', models.CharField(default='', max_length=200, verbose_name='参数类型描述')),
                ('par_cd', models.CharField(default='', max_length=30, verbose_name='参数代码')),
                ('par_nm', models.CharField(default='', max_length=200, verbose_name='参数描述')),
                ('f_par_cd', models.CharField(default='', max_length=30, verbose_name='父参数代码')),
                ('par_lv', models.CharField(default='', max_length=10, verbose_name='参数层级')),
                ('start_dt', models.CharField(default='', max_length=8, verbose_name='生效日期')),
                ('end_dt', models.CharField(default='', max_length=8, verbose_name='失效日期')),
                ('c_oper_no', models.CharField(default='', max_length=30, verbose_name='创建人员')),
                ('c_dt', models.CharField(default='', max_length=8, verbose_name='创建时间')),
                ('m_oper_no', models.CharField(default='', max_length=30, verbose_name='修改人员')),
                ('m_dt', models.CharField(default='', max_length=8, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '参数表',
                'verbose_name_plural': '参数表',
            },
        ),
        migrations.AlterModelOptions(
            name='extr',
            options={'verbose_name': '抽取表', 'verbose_name_plural': '抽取表'},
        ),
        migrations.AlterModelOptions(
            name='srcdb',
            options={'verbose_name': '数据源', 'verbose_name_plural': '数据源'},
        ),
    ]
