# Generated by Django 2.0.6 on 2018-07-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0006_auto_20180719_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefIndCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_no', models.CharField(default='', max_length=30, verbose_name='指标编号')),
                ('ind_proc', models.TextField(default='', verbose_name='处理语句')),
                ('tmp_tab', models.CharField(default='', max_length=200, verbose_name='临时表名')),
                ('calc_lvl', models.IntegerField(default='', verbose_name='计算层级')),
            ],
            options={
                'verbose_name': '指标表计算表',
                'verbose_name_plural': '指标表计算表',
            },
        ),
    ]
