# Generated by Django 2.0.6 on 2018-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0008_auto_20180723_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='extr',
            name='extr_data_dt',
            field=models.CharField(default='', max_length=10, verbose_name='数据日期'),
        ),
    ]
