# Generated by Django 2.0.6 on 2018-10-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0009_extr_extr_data_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extr',
            name='c_dt',
        ),
        migrations.RemoveField(
            model_name='extr',
            name='c_oper_no',
        ),
        migrations.RemoveField(
            model_name='extr',
            name='end_dt',
        ),
        migrations.RemoveField(
            model_name='extr',
            name='extr_no',
        ),
        migrations.RemoveField(
            model_name='extr',
            name='m_dt',
        ),
        migrations.RemoveField(
            model_name='extr',
            name='m_oper_no',
        ),
        migrations.RemoveField(
            model_name='extr',
            name='start_dt',
        ),
    ]
