# Generated by Django 2.0.6 on 2018-10-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0010_auto_20181008_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='extr',
            name='c_dt',
            field=models.CharField(default='', max_length=8, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='extr',
            name='c_oper_no',
            field=models.CharField(default='', max_length=30, verbose_name='创建人员'),
        ),
    ]
