# Generated by Django 2.0.6 on 2018-10-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0013_auto_20181009_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcdb',
            name='src_part',
            field=models.CharField(default='', max_length=3, verbose_name='抽取并行数'),
        ),
    ]
