# Generated by Django 2.0.6 on 2018-10-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus_spark', '0014_srcdb_src_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='extr',
            name='extr_cnt',
            field=models.CharField(default='', max_length=30, verbose_name='记录条数'),
        ),
        migrations.AlterField(
            model_name='defind',
            name='ind_data_dt',
            field=models.CharField(default='', max_length=8, verbose_name='数据日期'),
        ),
        migrations.AlterField(
            model_name='extr',
            name='extr_data_dt',
            field=models.CharField(default='', max_length=8, verbose_name='数据日期'),
        ),
    ]
